package com.jelekong.footballmatchschedule.database

object Favorite {
    const val TABLE_FAVORITE: String = "TABLE_FAVORITE"
    const val ID: String = "ID"
    const val EVENT_ID: String = "EVENT_ID"
    const val EVENT_DATE: String = "EVENT_DATE"
    const val EVENT_HOME_NAME: String = "EVENT_HOME_NAME"
    const val EVENT_AWAY_NAME: String = "EVENT_AWAY_NAME"
    const val EVENT_HOME_BADGE: String = "EVENT_HOME_BADGE"
    const val EVENT_AWAY_BADGE: String = "EVENT_AWAY_BADGE"
    const val EVENT_HOME_SCORE: String = "EVENT_HOME_SCORE"
    const val EVENT_AWAY_SCORE: String = "EVENT_AWAY_SCORE"
    const val EVENT_HOME_GOALS: String = "EVENT_HOME_GOALS"
    const val EVENT_AWAY_GOALS: String = "EVENT_AWAY_GOALS"
    const val EVENT_HOME_SHOTS: String = "EVENT_HOME_SHOTS"
    const val EVENT_AWAY_SHOTS: String = "EVENT_AWAY_SHOTS"
    const val EVENT_HOME_GOALS_KEEPER: String = "EVENT_HOME_GOALS_KEEPER"
    const val EVENT_AWAY_GOALS_KEEPER: String = "EVENT_AWAY_GOALS_KEEPER"
    const val EVENT_HOME_DEFENS: String = "EVENT_HOME_DEFENS"
    const val EVENT_AWAY_DEFENS: String = "EVENT_AWAY_DEFENS"
    const val EVENT_HOME_MIDFIELD: String = "EVENT_HOME_MIDFIELD"
    const val EVENT_AWAY_MIDFIELD: String = "EVENT_AWAY_MIDFIELD"
    const val EVENT_HOME_GOALS_FORWARD: String = "EVENT_HOME_GOALS_FORWARD"
    const val EVENT_AWAY_GOALS_FORWARD: String = "EVENT_AWAY_GOALS_FORWARD"
    const val EVENT_HOME_GOALS_SUBSTITUTES: String = "EVENT_HOME_GOALS_SUBSTITUTES"
    const val EVENT_AWAY_GOALS_SUBSTITUTES: String = "EVENT_AWAY_GOALS_SUBSTITUTES"
    const val EVENT_HOME_TEAM_ID: String = "EVENT_HOME_TEAM_ID"
    const val EVENT_AWAY_TEAM_ID: String = "EVENT_AWAY_TEAM_ID"
    const val EVENT_TIME: String = "EVENT_TIME"
    const val EVENT_SPORT: String = "EVENT_SPORT"
}